# Generated by Django 5.2.1 on 2025-05-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripmind", "0002_itinerary_is_public_itinerary_share_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
