# Generated by Django 5.2.1 on 2025-05-25 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripmind", "0003_itinerary_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
